---
title: "二項分布の比率の差の推定"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# clears workspace:  
rm(list=ls()) 
```


## 採用するモデルとモデルの記述

$n$回コイントスをして、$k$回表が出た。
コインの表が出る割合$\theta$を求める。

すなわち、$\theta$の事後分布を求める。

事前分布は以下の通り。
$$
  \theta \sim Beta(1, 1)
$$

確率モデル(尤度関数)は以下の通り。
$$
  k_1 \sim Bin(\theta, n_1) \\
  k_2 \sim Bin(\theta, n_2) 
$$



### Jagsのモデル記述

モデルをJags用に記述する。

```{r}
# Inferring a Rate
tmpJagsModel <- "
# Difference Between Two Rates
model{
   # Observed Counts
   k1 ~ dbin(theta1,n1)
   k2 ~ dbin(theta2,n2)
   # Prior on Rates
   theta1 ~ dbeta(1,1)
   theta2 ~ dbeta(1,1)
   # Difference Between Rates
   delta <- theta1-theta2
}
"
writeLines(tmpJagsModel, con="Rate_1.jags")  # モデルを一時ファイルに書き込む
```


### Stanのモデル記述

モデルをStan用に記述する。

```{r}
tmpStanModel <- "
// Difference Between Two Rates
data { 
  int<lower=1> n1; 
  int<lower=1> n2; 
  int<lower=0> k1;
  int<lower=0> k2;
} 
parameters {
  real<lower=0,upper=1> theta1;
  real<lower=0,upper=1> theta2;
} 
transformed parameters {
  real<lower=-1,upper=1> delta;
  delta <- theta1 - theta2;
}
model {
  // Prior Distribution for Rate Theta
  theta1 ~ beta(1, 1);
  theta2 ~ beta(1, 1);
  // Observed Counts
  k1 ~ binomial(n1, theta1);
  k2 ~ binomial(n2, theta2);
}
"
writeLines(tmpStanModel, con="Rate_1.stan")  # モデルを一時ファイルに書き込む
```


## サンプリング前準備

### 観測変数の設定

```{r}
k1 <- 5
k2 <- 7
n1 <- 10
n2 <- 10

data <- list("k1"=k1, "n1"=n1, "k2"=k2, "n2"=n2) 
```

### モニターするパラメータの設定

```{r}
# parameters to be monitored:	
parameters <- c("delta", "theta1", "theta2")
```

### thetaの初期値の設定

```{r}
myinits <-	list(
  list(theta1 = 0.1, theta2 = 0.9)
)
```

## サンプル生成

### 共通変数

```{r}
chains <- 1
thin <- 1
iter <- 20000
warmup <- 1000
```

### rjags


```{r}
library(rjags)

m <- jags.model(
  "Rate_1.jags",
  data     = data,
  inits    = myinits,
  n.chains = chains,
  n.adapt  = 0 )

update(m, warmup) # burn-in

samplesJags <- coda.samples(
  model          = m,
  variable.names = parameters,
  n.iter         = iter - warmup,
  thin           = thin)
```

### Stan

```{r}
library(rstan)

# The following command calls Stan with specific options.
# For a detailed description type "?rstan".
samplesStan <- stan(
  file="Rate_1.stan",   
  data=data, 
  init=myinits,  # If not specified, gives random inits
  pars=parameters,
  iter=iter, 
  chains=chains, 
  thin=thin,
  warmup = warmup,  # Stands for burn-in; Default = iter/2
  # seed = 123  # Setting seed; Default is random seed
)
# Now the values for the monitored parameters are in the "samples" object, 
# ready for inspection.
```



## bayesplotによる可視化

```{r}
library(bayesplot)
```

### ヒストグラム

```{r}
# Jags
mcmc_hist(samplesJags, par=c("delta"))
# Stan
mcmc_hist(samplesStan, par=c("delta"))
```

### 密度分布

```{r}
# Jags
mcmc_dens(samplesJags, par=c("delta"))
# Stan
mcmc_dens(samplesStan, par=c("delta"))
```

### トレースプロット

```{r}
# Jags
mcmc_trace(samplesJags, par=c("delta"))
# Stan
mcmc_trace(samplesStan, par=c("delta"))
```


### コレログラム

```{r}
# Jags
mcmc_acf_bar(samplesJags, par=c("delta"))
# Stan
mcmc_acf_bar(samplesStan, par=c("delta"))
```
