---
title: "coda.samples()の出力の受け取り方"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# clears workspace:  
rm(list=ls()) 
```


## 採用するモデルとモデルの記述

使うモデルはコレ

事前分布は以下の通り。
$$
  \theta \sim Beta(1, 1)
$$

確率モデル(尤度関数)は以下の通り。
$$
  k_1 \sim Bin(\theta, n_1) \\
  k_2 \sim Bin(\theta, n_2) 
$$

### Jagsのモデル記述

モデルをJags用に記述する。

```{r}
# Inferring a Rate
tmpJagsModel <- "
# Difference Between Two Rates
model{
   # Observed Counts
   k1 ~ dbin(theta1,n1)
   k2 ~ dbin(theta2,n2)
   # Prior on Rates
   theta1 ~ dbeta(1,1)
   theta2 ~ dbeta(1,1)
   # Difference Between Rates
   delta <- theta1-theta2
}
"
writeLines(tmpJagsModel, con="Rate_1.jags")  # モデルを一時ファイルに書き込む
```



## サンプリング前準備

### 観測変数の設定

```{r}
k1 <- 5
k2 <- 7
n1 <- 10
n2 <- 10

data <- list("k1"=k1, "n1"=n1, "k2"=k2, "n2"=n2) 
```

### モニターするパラメータの設定

```{r}
# parameters to be monitored:	
parameters <- c("delta", "theta1", "theta2")
```

### thetaの初期値の設定

```{r}
myinits <-	list(
  list(theta1 = 0.1, theta2 = 0.9)
)
```

## サンプル生成


```{r}
chains <- 1
thin <- 1
iter <- 20000
warmup <- 1000
```

```{r}
library(rjags)

m <- jags.model(
  "Rate_1.jags",
  data     = data,
  inits    = myinits,
  n.chains = chains,
  n.adapt  = 0 )

update(m, warmup) # burn-in

samplesJags <- coda.samples(
  model          = m,
  variable.names = parameters,
  n.iter         = iter - warmup,
  thin           = thin)
```


## 出力の受け取り方

ここからがポイント

```{r}
head(mcmc.list(samplesJags))
```


`obujectName[[1]][,parameterName]`で取得可能


```{r}
# オブジェクトsamplesJagsからパラメータ"delta"の出力を受け取る(※headで出力を抑えてる)
head(samplesJags[[1]][,"delta"])
```


```{r}
# オブジェクトsamplesJagsからパラメータ"theta1"の出力を受け取る(※headで出力を抑えてる)
head(samplesJags[[1]][,"theta1"])
```

```{r}
# オブジェクトsamplesJagsからパラメータ"theta2"の出力を受け取る(※headで出力を抑えてる)
head(samplesJags[[1]][,"theta2"])
```















